#2.1 Classement

Ouvrez les données d'apprentissage et de test à l'aide de la bibliothèque pandas. Combien y
a-t-il d'attributs dans ces 
chers ? Quels sont leurs types ? Quelle est la variable à prédire ?
Les classes sont-elles équilibrées dans les 
chiers ? Y a-t-il beaucoup de valeurs manquantes
dans les données ? Comment ces valeurs sont-elles représentées dans le 
cher ?

In [ ]:
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

#read input text and put data inside a data frame
AdultTrain  = pd.read_csv('/content/drive/MyDrive/TP2DataAnalytics/TP2/AdultEarnings/adult.train.csv')

print(AdultTrain.head())
print(AdultTrain.shape)
print(AdultTrain.dtypes)
'''
Les types de Variables
age                int64
workclass         object
fnlwgt             int64
education         object
education-num      int64
marital-status    object
occupation        object
relationship      object
race              object
sex               object
capital-gain       int64
capital-loss       int64
hours-per-week     int64
native-country    object
class             object
dtype: object

'''


   age         workclass  fnlwgt  education  education-num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   

       marital-status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capital-gain  capital-loss  hours-per-week native-country  class  
0          2174             0              40  United-States  <=50K  
1             0             0             

'\nLes types de Variables\nage                int64\nworkclass         object\nfnlwgt             int64\neducation         object\neducation-num      int64\nmarital-status    object\noccupation        object\nrelationship      object\nrace              object\nsex               object\ncapital-gain       int64\ncapital-loss       int64\nhours-per-week     int64\nnative-country    object\nclass             object\ndtype: object\n\n'

In [ ]:
AdultTest  = pd.read_csv('/content/drive/MyDrive/TP2DataAnalytics/TP2/AdultEarnings/adult.test.csv')

print(AdultTest.head())
print(AdultTest.shape)
print(AdultTest.dtypes)

   age  workclass  fnlwgt     education  education-num      marital-status  \
0   25    Private  226802          11th              7       Never-married   
1   38    Private   89814       HS-grad              9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm             12  Married-civ-spouse   
3   44    Private  160323  Some-college             10  Married-civ-spouse   
4   18          ?  103497  Some-college             10       Never-married   

          occupation relationship   race     sex  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4                  ?    Own-child  White  Female             0             0   

   hours-per-week native-country  class  
0       

In [ ]:
#la class a prédir est 'class'

In [ ]:
#Il y'a des valeurs manquantes dans la data car ils sont exprimé en ? 
#il y'a 4262 dans le train 
AdultTrain.isin(['?']).sum(axis=0)

age                  0
workclass         1836
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week       0
native-country     583
class                0
dtype: int64

In [ ]:
AdultTest.isin(['?']).sum(axis=0)
#il y' a 2203 valeurs manquantes dans le test

age                 0
workclass         963
fnlwgt              0
education           0
education-num       0
marital-status      0
occupation        966
relationship        0
race                0
sex                 0
capital-gain        0
capital-loss        0
hours-per-week      0
native-country    274
class               0
dtype: int64

In [ ]:
'''
Train :  Les classes ne sont pas équilibrés


    <=50K    12435
    >50K      7841

  Proportion 
    All = 32561
    <=50K    24720/All = 0.75 => 75% sont inférieure a 50k
    >50K    32561/All = 0.24 => 24% sont supérieure a 50k
'''

AdultTrain['class'].value_counts()

<=50K    24720
>50K      7841
Name: class, dtype: int64

In [ ]:


AdultTest['class'].value_counts()

'''
TEST : Les classes ne sont pas équilibrés

 
    <=50K    12435
    >50K      3846

  Proportion 
    All = 16281
    <=50K    12435/All = 0.76 => 70% sont inférieure a 50k
    >50K    3846/All = 0.236 => 23% sont supérieure a 50k
'''


'\nTEST : Les classes ne sont pas équilibrés\n\n \n    <=50K    12435\n    >50K      3846\n\n  Proportion \n    All = 16281\n    <=50K    12435/All = 0.76 => 70% sont inférieure a 50k\n    >50K    3846/All = 0.236 => 23% sont supérieure a 50k\n'

#Dummy classifier

Il s'agit d'un modèle de classification qui fait des prédictions sans essayer de trouver des modèles pattern dans les données.
Le modèle par défaut examine essentiellement l'étiquette la plus fréquente "most frequent" dans l'ensemble de données de formation et effectue des prédictions en fonction de cette étiquette tout simplement.

Généralement ce dernier est utiliser comme model de références, pour comparer les autres models.
Le dummy certe peut donner dans notre cas une très bonne accuracy car nous avons des données déséquilibrés, mais une très bonne accuracy ne signifie pas que le model fait un bon travail.


#Numerical TRANSFORMATION PART WITH StandarScaler

In [ ]:
#TRAIN
from sklearn.impute import SimpleImputer
#Les colonne numérique dans le train et test n'ont pas de valeurs manquantes

# Replace missing values by mean and scale numeric values
AdultTrainNUMERIQ = AdultTrain.select_dtypes(include='number')
#AdultTrainNUMERIQ = AdultTrain[['age', 'fnlwgt' , 'education-num' , 'capital-gain' , 'capital-loss' ,'hours-per-week']]
AdultTrainNUMERIQ.replace('?',np.NaN,inplace=True)
imp=SimpleImputer(missing_values=np.NaN, strategy='mean')
AdultTrainNUMERIQ=pd.DataFrame(imp.fit_transform(AdultTrainNUMERIQ))

#on a besoin d'applique ce filtre car dans certaine column on a des outliers alors on  a besoin de remmetre les donées sur la même échelle
from sklearn import preprocessing
scaler = preprocessing.StandardScaler()
AdultTrainNUMERIQ = scaler.fit_transform(AdultTrainNUMERIQ)

print(AdultTrainNUMERIQ)
X_train1 = AdultTrainNUMERIQ
y_train1= AdultTrain['class']


print("******************************************************")

#TEST
from sklearn.impute import SimpleImputer
#Les colonne numérique dans le train et test n'ont pas de valeurs manquantes

# Replace missing values by mean and scale numeric values
AdultTestNUMERIQ = AdultTest.select_dtypes(include='number')
AdultTestNUMERIQ.replace('?',np.NaN,inplace=True)
imp1=SimpleImputer(missing_values=np.NaN, strategy='mean')
AdultTestNUMERIQ=pd.DataFrame(imp1.fit_transform(AdultTestNUMERIQ))
#on a besoin d'applique ce filtre car dans certaine column on a des outliers alors on  a besoin de remmetre les données sur la même échelle
from sklearn import preprocessing
scaler = preprocessing.StandardScaler()
AdultTestNUMERIQ = scaler.fit_transform(AdultTestNUMERIQ)
print(AdultTestNUMERIQ)
X_test1 = AdultTestNUMERIQ
y_test1 = AdultTest['class']







[[ 0.03067056 -1.06361075  1.13473876  0.1484529  -0.21665953 -0.03542945]
 [ 0.83710898 -1.008707    1.13473876 -0.14592048 -0.21665953 -2.22215312]
 [-0.04264203  0.2450785  -0.42005962 -0.14592048 -0.21665953 -0.03542945]
 ...
 [ 1.42360965 -0.35877741 -0.42005962 -0.14592048 -0.21665953 -0.03542945]
 [-1.21564337  0.11095988 -0.42005962 -0.14592048 -0.21665953 -1.65522476]
 [ 0.98373415  0.92989258 -0.42005962  1.88842434 -0.21665953 -0.03542945]]
******************************************************
[[-0.99412926  0.35347399 -1.19686359 -0.14266185 -0.21806206 -0.03143184]
 [-0.05541716 -0.94239062 -0.41788553 -0.14266185 -0.21806206  0.7699177 ]
 [-0.77750339  1.39544986  0.75058156 -0.14266185 -0.21806206 -0.03143184]
 ...
 [-0.05541716  1.75522095  1.14007059 -0.14266185 -0.21806206  0.7699177 ]
 [ 0.37783458 -0.99842039  1.14007059  0.57664374 -0.21806206 -0.03143184]
 [-0.27204303 -0.0689392   1.14007059 -0.14266185 -0.21806206  1.57126723]]


/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5244: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5244: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,


CROSS VALIDATION With numerical attributes


In [ ]:

from sklearn.dummy import DummyClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn import tree
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn import metrics

print("CROSS VALIDATION With numerical attributes")
def accuracy_score(lst_classif,lst_classif_names,X,y):
    for clf,name_clf in zip(lst_classif,lst_classif_names):
        scores = cross_val_score(clf, X, y, cv=5)
        print("Accuracy of "+name_clf+" classifier on cross-validation: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

def confusion_matrix(lst_classif,lst_classif_names,X,y):
    for clf,name_clf in zip(lst_classif,lst_classif_names):
        predicted = cross_val_predict(clf, X, y, cv=5) 
        print("Accuracy of "+name_clf+" classifier on cross-validation: %0.2f" % metrics.accuracy_score(y, predicted))
        print(metrics.confusion_matrix(y, predicted))


dummycl = DummyClassifier(strategy="most_frequent")
gmb = GaussianNB()
dectree = tree.DecisionTreeClassifier()
rdforest = RandomForestClassifier()
logreg = LogisticRegression(solver="liblinear")
svc = svm.SVC(gamma='scale')

lst_classif = [dummycl, gmb, dectree, rdforest, logreg, svc]
lst_classif_names = ['Dummy', 'Naive Bayes', 'Decision tree', 'Random Forest', 'Logistic regression', 'SVM']

accuracy_score(lst_classif,lst_classif_names,X_train1,y_train1)
confusion_matrix(lst_classif,lst_classif_names,X_train1,y_train1)

'''
le dummy 
[[24720     0]
 [ 7841     0]]

 a toujourd classer toutes les instance dans la classes 0 c a d income<=50k 
 on voit bient que 24720 classé correctement or 7841 qui était de la class 1 on était classé comme class 0
'''


CROSS VALIDATION With numerical attributes
Accuracy of Dummy classifier on cross-validation: 0.76 (+/- 0.00)
Accuracy of Naive Bayes classifier on cross-validation: 0.80 (+/- 0.01)
Accuracy of Decision tree classifier on cross-validation: 0.77 (+/- 0.01)
Accuracy of Random Forest classifier on cross-validation: 0.81 (+/- 0.01)
Accuracy of Logistic regression classifier on cross-validation: 0.82 (+/- 0.01)
Accuracy of SVM classifier on cross-validation: 0.82 (+/- 0.01)
Accuracy of Dummy classifier on cross-validation: 0.76
[[24720     0]
 [ 7841     0]]
Accuracy of Naive Bayes classifier on cross-validation: 0.80
[[23493  1227]
 [ 5411  2430]]
Accuracy of Decision tree classifier on cross-validation: 0.77
[[20908  3812]
 [ 3623  4218]]
Accuracy of Random Forest classifier on cross-validation: 0.81
[[22266  2454]
 [ 3851  3990]]
Accuracy of Logistic regression classifier on cross-validation: 0.82
[[23452  1268]
 [ 4750  3091]]
Accuracy of SVM classifier on cross-validation: 0.82
[[23895 

'\nle dummy \n[[24720     0]\n [ 7841     0]]\n\n a toujourd classer toutes les instance dans la classes 0 c a d income<=50k \n on voit bient que 24720 classé correctement or 7841 qui était de la class 1 on était classé comme class 0\n'

#CATEGORICAL TRANSFORMATION PART WITH OneHotEncoder

In [ ]:

#Train

# Replace missing values by mode and discretize categorical values
AdultTrainCATEGO = AdultTrain.select_dtypes(exclude='number').drop('class',axis=1)

AdultTrainCATEGO.replace('?',np.NaN,inplace=True)
imputer = SimpleImputer(missing_values=np.NaN, strategy='most_frequent')
AdultTrainCATEGO=pd.DataFrame(imputer.fit_transform(AdultTrainCATEGO))

'''
AdultTrainCATEGO = pd.get_dummies(AdultTrainCATEGO)
AdultTrainCATEGO.head()
print(AdultTrainCATEGO)
'''

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
AdultTrainCATEGO=AdultTrainCATEGO.apply(lambda col: le.fit_transform(col))
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

#One-hot-encode the categorical columns.
#Unfortunately outputs an array instead of dataframe.
array_hot_encoded = ohe.fit_transform(AdultTrainCATEGO).toarray()

#Convert it to df
AdultTrainCATEGO = pd.DataFrame(array_hot_encoded, index=AdultTrain.index)


X_train2 = AdultTrainCATEGO
y_train2= AdultTrain['class']


print(AdultTrainCATEGO)



print("******************************************************")





#Test

# Replace missing values by mean and discretize categorical values
AdultTestCATEGO = AdultTest.select_dtypes(exclude='number').drop('class',axis=1)
AdultTestCATEGO.replace('?',np.NaN,inplace=True)
imputer = SimpleImputer(missing_values=np.NaN, strategy='most_frequent')
AdultTestCATEGO=pd.DataFrame(imputer.fit_transform(AdultTestCATEGO))

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
AdultTestCATEGO=AdultTestCATEGO.apply(lambda col: le.fit_transform(col))
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

#One-hot-encode the categorical columns.
#Unfortunately outputs an array instead of dataframe.
array_hot_encoded = ohe.fit_transform(AdultTestCATEGO).toarray()

#Convert it to df
AdultTestCATEGO = pd.DataFrame(array_hot_encoded, index=AdultTest.index)





        0    1    2    3    4    5    6    7    8    9   ...   89   90   91  \
0      0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1      0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2      0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3      0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  0.0   
4      0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
32556  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
32557  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
32558  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
32559  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
32560  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

        92   93   94   95   96   97   98  
0      0

CROSS VALIDATION With Categorical attributes

In [ ]:
print("CROSS VALIDATION With Categorical attributes")
def accuracy_score(lst_classif,lst_classif_names,X,y):
    for clf,name_clf in zip(lst_classif,lst_classif_names):
        scores = cross_val_score(clf, X, y, cv=5)
        print("Accuracy of "+name_clf+" classifier on cross-validation: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

def confusion_matrix(lst_classif,lst_classif_names,X,y):
    for clf,name_clf in zip(lst_classif,lst_classif_names):
        predicted = cross_val_predict(clf, X, y, cv=5) 
        print("Accuracy of "+name_clf+" classifier on cross-validation: %0.2f" % metrics.accuracy_score(y, predicted))
        print(metrics.confusion_matrix(y, predicted))


dummycl = DummyClassifier(strategy="most_frequent")
gmb = GaussianNB()
dectree = tree.DecisionTreeClassifier()
rdforest = RandomForestClassifier()
logreg = LogisticRegression(solver="liblinear")
svc = svm.SVC(gamma='scale')

lst_classif = [dummycl, gmb, dectree, rdforest, logreg, svc]
lst_classif_names = ['Dummy', 'Naive Bayes', 'Decision tree', 'Random Forest', 'Logistic regression', 'SVM']

accuracy_score(lst_classif,lst_classif_names,X_train2,y_train2)
confusion_matrix(lst_classif,lst_classif_names,X_train2,y_train2)


CROSS VALIDATION With Categorical attributes
Accuracy of Dummy classifier on cross-validation: 0.76 (+/- 0.00)
Accuracy of Naive Bayes classifier on cross-validation: 0.51 (+/- 0.05)
Accuracy of Decision tree classifier on cross-validation: 0.82 (+/- 0.00)
Accuracy of Random Forest classifier on cross-validation: 0.82 (+/- 0.00)
Accuracy of Logistic regression classifier on cross-validation: 0.83 (+/- 0.01)
Accuracy of SVM classifier on cross-validation: 0.83 (+/- 0.01)
Accuracy of Dummy classifier on cross-validation: 0.76
[[24720     0]
 [ 7841     0]]
Accuracy of Naive Bayes classifier on cross-validation: 0.51
[[ 9033 15687]
 [  397  7444]]
Accuracy of Decision tree classifier on cross-validation: 0.82
[[22373  2347]
 [ 3589  4252]]
Accuracy of Random Forest classifier on cross-validation: 0.82
[[22539  2181]
 [ 3522  4319]]
Accuracy of Logistic regression classifier on cross-validation: 0.83
[[22908  1812]
 [ 3725  4116]]
Accuracy of SVM classifier on cross-validation: 0.83
[[2290

# CROSS VALIDATION AVEC les attributs numériques et catégoriels

Scikit-learn fournit une classe ColumnTransformer qui enverra des colonnes spécifiques à un transformateur spécifique, ce qui facilite l'ajustement d'un modèle prédictif unique sur un ensemble de données qui combine les deux types de variables.

Ici nous allons cree un pipeline

Ici, notre objectif est de prédire le revenu qui peut être soit 0 soit 1 classification binaire (moins de 50 000 ou plus de 50 000) et nous voulons identifier une relation entre notre résultat (revenu) et les autres caractéristiques indépendantes (éducation, classe ouvrière, sexe, etc.). 

In [ ]:
print("TRAIN AND TEST THE MODEL with numeriq columns")

from sklearn.dummy import DummyClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn import tree
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.compose import ColumnTransformer
from sklearn.compose import make_column_selector as selector
from sklearn.compose import ColumnTransformer

dataTrain=AdultTrain
target_name = "class"
target = dataTrain[target_name]
dataTrain = dataTrain.drop(columns=[target_name])
dataTrain.replace('?',np.NaN,inplace=True)


##################################################

dataTest=AdultTest
target_name = "class"
targetest = dataTest[target_name]
dataTest = dataTest.drop(columns=[target_name])
dataTest.replace('?',np.NaN,inplace=True)

TRAIN AND TEST THE MODEL with numeriq columns


In [ ]:
cols=['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss', 'hours-per-week','workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country']
[dataTrain.columns.get_loc(c) for c in cols if c in dataTrain]

[0, 2, 4, 10, 11, 12, 1, 3, 5, 6, 7, 8, 9, 13]

In [ ]:
from sklearn.pipeline import Pipeline,make_pipeline
#https://scikit-learn.org/stable/auto_examples/compose/plot_column_transformer_mixed_types.html

In [ ]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
numeric_features = ['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss', 'hours-per-week']
numeric_transformer = Pipeline(
    steps=[("imputer", SimpleImputer(missing_values=np.NaN, strategy='mean')), ("scaler",  StandardScaler())]
)
categorical_features = ['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country']
# NB :I had to use A sparse=false because by default it s true, and this on is not matrix containg a lot of zeros, could skip it
#it was the problem of my errors for a long moment 
categorical_transformer = Pipeline(
    steps=[('imputer2',SimpleImputer(missing_values=np.NaN, strategy='most_frequent')), ('ohe',OneHotEncoder(sparse=False,handle_unknown='ignore')) ]
)

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features),
    ]
)
from sklearn.preprocessing import FunctionTransformer

def accuracy_score_PIPELINE(lst_classif,lst_classif_names,X,y):
    for clf,name_clf in zip(lst_classif,lst_classif_names):
        model = Pipeline(
    steps=[("preprocessor", preprocessor), ("classifier", clf)]
)
        scores = cross_val_score(model,  X, y, cv=5)
        print("Accuracy of "+name_clf+" classifier on cross-validation: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

def confusion_matrix_PIPELINE(lst_classif,lst_classif_names,X,y):
    for clf,name_clf in zip(lst_classif,lst_classif_names):
        model = Pipeline(
    steps=[("preprocessor", preprocessor), ("classifier", clf)]
)
        predicted = cross_val_predict(model, X, y, cv=5) 
        print("Accuracy of "+name_clf+" classifier on cross-validation: %0.2f" % metrics.accuracy_score(y, predicted))
        print(metrics.confusion_matrix(y, predicted))


accuracy_score_PIPELINE(lst_classif,lst_classif_names,dataTrain, target)
confusion_matrix_PIPELINE(lst_classif,lst_classif_names,dataTrain, target)

Accuracy of Dummy classifier on cross-validation: 0.76 (+/- 0.00)
Accuracy of Naive Bayes classifier on cross-validation: 0.54 (+/- 0.03)
Accuracy of Decision tree classifier on cross-validation: 0.81 (+/- 0.01)
Accuracy of Random Forest classifier on cross-validation: 0.85 (+/- 0.01)
Accuracy of Logistic regression classifier on cross-validation: 0.85 (+/- 0.01)
Accuracy of SVM classifier on cross-validation: 0.86 (+/- 0.01)
Accuracy of Dummy classifier on cross-validation: 0.76
[[24720     0]
 [ 7841     0]]
Accuracy of Naive Bayes classifier on cross-validation: 0.54
[[10145 14575]
 [  388  7453]]
Accuracy of Decision tree classifier on cross-validation: 0.81
[[21614  3106]
 [ 2940  4901]]
Accuracy of Random Forest classifier on cross-validation: 0.85
[[22921  1799]
 [ 2969  4872]]
Accuracy of Logistic regression classifier on cross-validation: 0.85
[[23029  1691]
 [ 3151  4690]]
Accuracy of SVM classifier on cross-validation: 0.86
[[23257  1463]
 [ 3225  4616]]


Sélectionnez le meilleur modèle testé lors des con
gurations précédentes et apprenez-le sur
l'ensemble des données d'apprentissage. Quelle est la performance mesurée avec ce modèle sur
le corpus de test ? Quelle est la classe pour laquelle la prédiction fait le plus d'erreurs ?


In [ ]:
#Entrainer le model et tester 
clf = svm.SVC(gamma='scale')
name_clf = "Support vector machine"

model = Pipeline(
steps=[("preprocessor", preprocessor), ("classifier", clf)])
model.fit(dataTrain, target )
# TODO
y_pred =  model.predict(dataTest)

print('Accuracy of '+name_clf+' classifier on training set: {:.2f}'
      .format(model.score(dataTrain, target)))
print('Accuracy of '+name_clf+' classifier on test set: {:.2f}'
  .format(model.score(dataTest, targetest)))
print(confusion_matrix(targetest, y_pred))

Accuracy of Support vector machine classifier on training set: 0.87
Accuracy of Support vector machine classifier on test set: 0.86
[[11720   715]
 [ 1594  2252]]
